required=[
  "honnef.co/go/tools/cmd/gosimple",
  "github.com/golangci/golangci-lint",
  "github.com/client9/misspell/cmd/misspell",
  "golang.org/x/lint/golint",
  "github.com/gordonklaus/ineffassign",
  "github.com/tsenart/deadcode",
]

[[constraint]]
  name = "github.com/chzyer/readline"
  branch = "master"

[[constraint]]
  name = "github.com/juju/ansiterm"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/lint"
